#Name: Hadar Amira
#ID: 207026527
#Name: zvi liebskind 
#ID: 305798752

server.out: compileAll
	g++ *.o -o ../../exe/server.out
	rm -f *.o

compileAll: *.h *.cpp
	    g++ -c *.cpp

run:
	./server.out 
