#Name: Hadar Amira
#ID: 207026527
#Name: zvi liebskind 
#ID: 305798752

ReversiGame.out: compileAll
	g++ *.o -o ../../exe/ReversiGame.out
	rm -f *.o

compileAll: *.h *.cpp
	    g++ -c *.cpp

run:
	./ReversiGame.out 
